/** Options that control crawling, filtering, extraction, and request behavior. */
export type Options = {
  /**
   * Maximum number of requests made at the same time.
   *
   * @default 3
   */
  concurrency?: number

  /**
   * Micromatch patterns matched against `URL.pathname` values.
   *
   * When provided, only matching pages are included in the result. Pages that do
   * not match are also skipped for traversal unless `follow` is enabled. The
   * starting URL is always fetched regardless of this option.
   */
  match?: string[]

  /**
   * Continue crawling links from pages that fail `match` or `exclude` filters.
   *
   * Enable this when index pages, home pages, or section pages should act as
   * stepping stones to discover matching content pages.
   *
   * @default false
   */
  follow?: boolean

  /**
   * CSS selector for the element whose HTML should be converted to Markdown.
   *
   * Pass a function to choose a selector per pathname. When omitted, Sitefetch
   * converts the cleaned document.
   */
  contentSelector?:
    | string
    | ((ctx: { pathname: string }) => string | void | undefined)

  /**
   * Maximum number of pages to include in the result.
   *
   * Pass `0` to disable link-following and fetch only the explicit starting
   * URL or URLs.
   */
  limit?: number

  /**
   * Delay, in milliseconds, before retrying a request after a 429 response.
   *
   * @default 30000
   */
  retryDelay?: number

  /**
   * Micromatch patterns matched against `URL.pathname` values to omit pages.
   *
   * The starting URL is always fetched regardless of this option. When `follow`
   * is enabled, excluded pages may still be visited for link discovery, but they
   * are not included in the result.
   */
  exclude?: string[]

  /**
   * Custom fetch implementation used for all requests.
   *
   * This is useful for tests, custom headers, caching, proxying, or alternate
   * runtimes. The function receives the URL and the `RequestInit` generated by
   * Sitefetch.
   */
  fetch?: (url: string, init: RequestInit) => Promise<Response>
}

/** A fetched page after readable HTML has been converted to Markdown. */
export type Page = {
  /** Best-effort page title from `readdown` metadata or the document `<title>`. */
  title: string

  /** Final URL used for Markdown extraction. */
  url: string

  /** Markdown content extracted from the page. */
  content: string
}

/** Fetched pages keyed by URL pathname. */
export type FetchSiteResult = Map<string, Page>
